image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/cibase:0.6.0

stages:
  - mvn-package

maven-build:
  stage: mvn-package
  script:
    - - mvn clean && mvn install -U -DskipTests=false
    - maven_sonar

.auto_devops: &auto_devops |
  function maven_sonar(){
    if [[ ${CI_COMMIT_REF_NAME} == develop* ]];then
     mvn -B verify sonar:sonar -U -DskipTests=false  -Dsonar.inclusions=**/data/convert/**/*,**/data/convert/**/*.java  -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.gitlab.project_id=$CI_PROJECT_PATH -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.analysis.serviceGroup=$GROUP_NAME -Dsonar.analysis.commitId=$CI_COMMIT_SHA
    else
     mvn -B package -DskipTests=true
    fi
  }

before_script:
  - *auto_devops

